name: 报告 Bug
description: 报告 失效/误触 规则Bug
body:
  - type: markdown
    attributes:
      value: |
        请按照此模版填写 BUG 界面的快照
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 我确保提供 误触/不执行规则 的界面的快照, 否则我同意维护者直接关闭issue
          required: true
        - label: 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD](https://github.com/gkd-kit/gkd/releases/latest)
          required: true
        - label: 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
          required: true
        - label: 我确保已阅读 [#120](https://github.com/AIsouler/GKD_subscription/issues/120)，否则我同意维护者直接关闭issue
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: |
        请输入 误触/不执行规则 的界面的快照, BUG描述及其复现步骤(视频/截图)或者生成的快照链接, 也可在后面补充其它信息
        请注意: 
        1. 不提供快照或者仅提供截图的 issue 将被自动关闭
        2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭
      description: |
        快照是一个 zip 文件, 快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本, 按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照, 上传文件或者生成链接并粘贴到下面的输入框\
        ![img](https://raw.githubusercontent.com/AIsouler/GKD_subscription/e08028b4a4464640f39927059b9b502760111e8e/Snapshot.png)\
        此外需提供 [主页-点击记录] 的截图\
    validations:
      required: true
