name: 报告 Bug
description: 报告 误触 规则Bug
body:
  - type: markdown
    attributes:
      value: |
        ##在提交问题之前，请确保您完成以下操作
        1. 我确保 **提供 误触界面 的快照（不要提供截图，截图没有任何作用），并说明是哪一条规则误触**
        2. 我确保使用的是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD](https://github.com/gkd-kit/gkd/releases/latest)
        3. 检查这个问题是否属于 [本项目维护的规则](https://github.com/AIsouler/GKD_subscription) 导致的
        4. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭
  - type: textarea
    id: bug-description
    attributes:
      label: |
        请输入 误触界面 的快照或者生成的链接，也可在后面补充其它信息
      description: |
        快照是一个 zip 文件，快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本，按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照，上传文件或者生成链接并粘贴到下面的输入框\
        ![img](https://raw.githubusercontent.com/AIsouler/GKD_subscription/e08028b4a4464640f39927059b9b502760111e8e/Snapshot.png)
    validations:
      required: true
