name: 请求适配
title: '[Feature] '
description: 请求增加适配 APP 规则
body:
  - type: markdown
    attributes:
      value: |
        ## 在提交问题之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！
        ## 在提交问题之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！
        ## 在提交问题之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！

        1. **提供需要适配界面的快照（不要提供截图，截图没有任何作用，不要使用截屏快照），快照获取方式如下图**
        2. 如果是需要点击多次才能关闭的情况，那么必须提供每一次点击页面的快照
        3. 检查全局规则是否开启
        4. 检查使用的是否是 [最新版订阅](https://github.com/AIsouler/GKD_subscription/releases/latest) 和 [最新版GKD](https://github.com/gkd-kit/gkd/releases/latest)
        5. 阅读 [不予适配情况合集](https://github.com/AIsouler/GKD_subscription/issues/480)
        6. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭
        7. 一个issue内可提供多个快照，没必要对同一个应用开启多个issue
        8. 上传文件时请等待文件名前面的 Uploading 消失后再提交，否则文件将会上传失败
  - type: textarea
    id: feature-description
    attributes:
      label: |
        请提供 需要适配界面 的快照（不要提供截图！！！不要使用截屏快照！！！），也可补充说明
      description: |
        快照是一个 zip 文件，快照链接是类似 "https://i.gkd.li/i/XXXXXXXX" 的文本，按照如下方式可获得快照信息

        按照下面的截图示例来获取界面快照，上传文件或者生成链接并粘贴到下面的输入框，如果是需要多个点击如 [点击关闭按钮->出现关闭弹窗->点击关闭原因] 这种类型，则需要填写每个点击界面的快照\
        ![img](https://raw.githubusercontent.com/AIsouler/GKD_subscription/refs/heads/main/Snapshot.png)
    validations:
      required: true
